USE [master]
GO

/****** Object:  Database [KafkaReplication]    Script Date: 3/20/2024 4:27:49 PM ******/
CREATE DATABASE [KafkaReplication]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KafkaReplication', FILENAME = N'/var/opt/mssql/data/KafkaReplication.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KafkaReplication_log', FILENAME = N'/var/opt/mssql/data/KafkaReplication_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KafkaReplication].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KafkaReplication] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KafkaReplication] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KafkaReplication] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KafkaReplication] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KafkaReplication] SET ARITHABORT OFF 
GO

ALTER DATABASE [KafkaReplication] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KafkaReplication] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KafkaReplication] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KafkaReplication] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KafkaReplication] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KafkaReplication] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KafkaReplication] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KafkaReplication] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KafkaReplication] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KafkaReplication] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KafkaReplication] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KafkaReplication] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KafkaReplication] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KafkaReplication] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KafkaReplication] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KafkaReplication] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KafkaReplication] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KafkaReplication] SET RECOVERY FULL 
GO

ALTER DATABASE [KafkaReplication] SET  MULTI_USER 
GO

ALTER DATABASE [KafkaReplication] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KafkaReplication] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KafkaReplication] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KafkaReplication] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [KafkaReplication] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [KafkaReplication] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [KafkaReplication] SET QUERY_STORE = ON
GO

ALTER DATABASE [KafkaReplication] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [KafkaReplication] SET  READ_WRITE 
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- Accesses table

CREATE TABLE [dbo].[accesses](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ip] [nchar](15) NOT NULL,
	[origin_id] [int] NOT NULL,
	[changes_date] [datetime] NOT NULL,
 CONSTRAINT [PK_accesses] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[accesses] ADD  CONSTRAINT [DF_accesses_changes_date]  DEFAULT (getdate()) FOR [changes_date]
GO

-- Users table

CREATE TABLE [dbo].[users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[first_name] [nvarchar](255) NOT NULL,
	[last_name] [nvarchar](255) NOT NULL,
	[email] [nvarchar](255) NOT NULL,
	[password] [nchar](255) NOT NULL,
	[changed_date] [datetime] NOT NULL,
 CONSTRAINT [PK_users_id] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[users] ADD  CONSTRAINT [DF_users_changed_date]  DEFAULT (getdate()) FOR [changed_date]
GO

-- Articles table

CREATE TABLE [dbo].[articles](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NOT NULL,
	[title] [nvarchar](255) NOT NULL,
	[context_text] [text] NOT NULL,
	[changed_date] [datetime] NOT NULL,
 CONSTRAINT [PK_articles] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[articles] ADD  CONSTRAINT [DF_articles_changed_date]  DEFAULT (getdate()) FOR [changed_date]
GO

ALTER TABLE [dbo].[articles]  WITH CHECK ADD  CONSTRAINT [FK_articles_users] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
GO

ALTER TABLE [dbo].[articles] CHECK CONSTRAINT [FK_articles_users]
GO



